handle player push to api behaviour internally
Stremio/stremio-core pull request #430
Opened 2023-02-16 09:39 UTC by TheBeastLT

Handle `push_to_api` behavior handling internally, instead of each individual implementation doing something differently and missing some push or having them too often.
Now it will push to api when updating time and check if at least 30s passed since the last update. As `update_time` on every movie tick it should work just fine. 
Also push to api when stopping the movie and when unloading the model.

2023-02-16 11:44 UTC, elpiel requested changes

2023-02-16 11:44 UTC, elpiel commented on src/models/player.rs
> +                        || E::now() - self.api_push_time.unwrap() >= Duration::seconds(30)
I'm not sure  `unwrap()` here is justified. What if the DateTime is None?
When do we actually set this DateTime and if we expect for it to always be there, then it should not be `Option`.

2023-02-16 11:47 UTC, elpiel commented on src/models/player.rs
> +                        || E::now() - self.api_push_time.unwrap() >= Duration::seconds(30)
Also, this should be `match`ed, not `if is_none || .unwrap()`

2023-02-16 12:02 UTC, TheBeastLT commented on src/models/player.rs
> +                        || E::now() - self.api_push_time.unwrap() >= Duration::seconds(30)
> When do we actually set this DateTime

Yes, forgot to update it.

> Also, this should be matched, not if is_none || .unwrap()

I've changed it to use `unwrap_or_default`, cuz that matches both conditions and is more concise than using `match`.
Or maybe it would be even better to declare `pub api_push_time: DateTime<Utc>,` and it would then use Default value of Epoch for it, then the condition could be just `E::now() - self.api_push_time >= Duration::seconds(30)`

2023-03-06 12:52 UTC, elpiel commented on src/models/player.rs
> +fn push_to_library(library_item: &Option<LibraryItem>) -> Effects {
To follow convention it should be named: `update_library_item`

2023-03-06 12:52 UTC, elpiel commented on src/models/player.rs
> +    pub push_library_item_time: DateTime<Utc>,
I see where we replace the value with the new `DateTime` (`E::now()`) but when is this value set initially?

I'm still hesitant of whether or not we should use `Option`

2023-03-11 17:33 UTC, TheBeastLT commented on src/models/player.rs
> +    pub push_library_item_time: DateTime<Utc>,
It's set from the Default trait, which is Epoch. Each model is created via Model::new constructor. This is done in the core-web and core-kotlin.

2023-03-14 10:22 UTC, elpiel commented on src/models/player.rs
> +    pub push_library_item_time: DateTime<Utc>,
Right now DateTime does not support Default, meaning that this does not compile.
We should set the default value ourselves or use `Option`

2023-03-14 10:29 UTC, TheBeastLT commented on src/models/player.rs
> +    pub push_library_item_time: DateTime<Utc>,
DateTime does impl Default https://docs.rs/chrono/latest/chrono/struct.DateTime.html

2023-03-23 12:14 UTC, elpiel commented on src/models/player.rs
> +    pub push_library_item_time: DateTime<Utc>,
I've added derivative with default Timestamp of the Epoc, this it make sure we update the `LibraryItem` on `TimeChanged`

2023-03-23 12:15 UTC, elpiel approved these changes

2023-03-29 08:15 UTC, merged