fix: mark as watched behavior for meta_details
Stremio/stremio-core pull request #650
Opened 2024-03-11 13:40 UTC by tymmesyde

Don't forward the event as `LibraryItemMarkAsWatched`
Use `flagged_watched` instead of updating `times_watched`

2024-03-20 11:47 UTC, elpiel approved these changes
LGTM!

2024-03-20 12:02 UTC, elpiel commented
> i accept tim's proposal to not increment times watched.. but maybe we should just not increment it over 1? (yet still change it from 0 to 1 the first time u mark as watched)
From @jaruba 

@tymmesyde if you agree, let's just make the change and merge this PR.

2024-04-21 08:25 UTC, unclekingpin requested changes
I have issues with this PR.
flagged_watched is not the best name for this flag, but its supposed to be used only in the player, when the user reach some threshold so that we dont do unnesesary operation in the watched bitfield.

How can i reproduce this https://github.com/Stremio/stremio-tasks/issues/203
The only way i could think of is if the times_watched counter already had u32::MAX and we try to do library_item.state.times_watched += 1; instead of library_item.state.times_watched.saturating_add(1)

2024-04-26 12:18 UTC, elpiel commented
#674 merged instead, this PR is no longer needed

2024-04-26 12:18 UTC, closed without merging