feat: ExternalPlayerLink - Add moonplayer for ios
Stremio/stremio-core pull request #709
Opened 2024-07-26 09:03 UTC by elpiel

2024-07-26 13:32 UTC, kKaskak requested changes

2024-07-26 13:32 UTC, kKaskak commented on src/deep_links/mod.rs
> +    /// Vision Pro os
```suggestion
    /// VisionOS
```

2024-07-26 16:46 UTC, tymmesyde commented
`visionos` fields are missing for VLC and Outplayer
We can probably assume that they are the same as ios

2024-07-29 11:30 UTC, kKaskak approved these changes

2024-07-31 06:44 UTC, merged