Add subtitles size and offset for StreamItemState
Stremio/stremio-core pull request #735
Opened 2024-11-12 11:56 UTC by tymmesyde

2024-11-13 15:53 UTC, kKaskak approved these changes

2024-11-14 09:41 UTC, elpiel commented on src/types/streams/streams_item.rs
>      #[serde(skip_serializing_if = "Option::is_none")]
```suggestion
    #[serde(default, skip_serializing_if = "Option::is_none")]
```

2024-11-14 09:41 UTC, elpiel commented on src/types/streams/streams_item.rs
> +    #[serde(skip_serializing_if = "Option::is_none")]
```suggestion
    #[serde(default, skip_serializing_if = "Option::is_none")]
```

2024-11-14 09:43 UTC, elpiel requested changes
These are the only changes that should guard against failing deserialization of already existing `StreaamItemState`s in the `StreamsBucket`

2024-11-14 09:49 UTC, elpiel commented on src/types/streams/streams_item.rs
> +    pub subtitle_size: Option<u64>,
```suggestion
    /// Subtitles size, platform dependent units
    pub subtitle_size: Option<u64>,
```

2024-11-14 09:49 UTC, elpiel commented on src/types/streams/streams_item.rs
> +    pub subtitle_offset: Option<u64>,
```suggestion
    /// Vertical offset of the subtitles, platform dependent units
    pub subtitle_offset: Option<u64>,
```

2024-11-14 09:56 UTC, elpiel approved these changes

2024-11-14 09:56 UTC, merged